version: '3.8'

services:
  vectordb:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=librechat-rag
      - RAG_PORT=${RAG_PORT:-8000}
    ports:
      - "${RAG_PORT:-8000}:${RAG_PORT:-8000}"
    networks:
      - databases
    env_file:
      - .env

volumes:
  pgdata2:

networks:
  databases:
    external: true
